### ISSUE TITLE
[어드민]>[가게입점하기]>쿠폰 페이지 이슈(쿠폰 활성화)

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/MVP_QA#11]
[테스트 환경]
안드로이드-크롬

[현재 문제점]
![KakaoTalk_Photo_2024-06-20-21-12-06](https://github.com/Dumbs-app/MVP_QA/assets/162934244/887a17df-fa88-4265-85cb-3bbaa35a8550)

설계에는 쿠폰 on 최대 5건 활성화 가능이지만 6건 가능 이슈

[개선사항]

5건까지만 On하도록 조정

**Comment by Dumbs-app** [comment]
확인했슴다~!
