### ISSUE TITLE
[어드민]>[가게입점하기]>공연 페이지 이슈  (인스타 한글)

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/MVP_QA#12]
[테스트 환경]
안드로이드-크롬

[현재 문제점]

![KakaoTalk_Photo_2024-06-20-21-27-36 007](https://github.com/Dumbs-app/MVP_QA/assets/162934244/770443ff-2b3f-4c5a-b644-630152afac2b)
게스트 추가 인스타에 한글 입력 이슈

[개선사항]

영어만 가능하게 조정

**Comment by heyman333** [comment]
@hateyoon 수정완료

**Comment by hateyoon** [comment]
감사합니다
