### ISSUE TITLE
[어드민]>[가게입점하기]>공연 페이지 이슈 (입장료)

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/MVP_QA#13]
[테스트 환경]
안드로이드-크롬

[현재 문제점]

![KakaoTalk_Photo_2024-06-20-21-27-36 006](https://github.com/Dumbs-app/MVP_QA/assets/162934244/82939cf7-c2d7-4586-a2d2-7b07786819b0)

설계 체크가 빠져있긴 했지만 입장료 입력후 취소하기 버튼 클릭시 기능 발현x

[개선사항]
취소하기 버튼 동작or 저장하기 버튼은 있으면 좋겠습니다

**Comment by heyman333** [comment]
@hateyoon 취소하기 버튼을 삭제 하도록 하겠습니다 !!

**Comment by Dumbs-app** [comment]
확인확인~!
