### ISSUE TITLE
[어드민] 정보 반영 요청하기 > '저장하기' 로 버튼 텍스트 변경 및 추가

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/MVP_QA#26]
[테스트 환경]
맥 & iOS & Android

[현재 문제점]

'가게 정보', '영업시간 및 입장료', '메뉴' 페이지에서
최하단 버튼 텍스트가 '정보 반영 요청하기' 로 되어 있습니다.

'정보 반영 요청하기' 텍스트가 어렵다는 의견이 있어
'저장하기'로 바꾸고자 합니다.

[개선사항]

<img width="548" alt="image" src="https://github.com/Dumbs-app/MVP_QA/assets/165153023/237e884b-eb6f-4afa-b52c-cb50a2625572">

1. 모든 '정보 반영 요청하기' 버튼 텍스트 -> '저장하기'로 변경
2. '저장하기' 버튼 밑에 '저장 후 정보 반영에 2-3일이 소요됩니다' 텍스트 추가 부탁드립니다.

Figma 참고 링크
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/덤즈?node-id=1-29926&t=Fp3TCpdoBIYCqrL6-11

**Comment by Dumbs-app** [comment]
반영확인했습니다!
