### ISSUE TITLE
[어드민] 가게정보 관련 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/MVP_QA#4]
[테스트 환경]
맥 > 크롬
로그인 후 접근

[현재 문제점]
1. '보관함이 없어요' 선택시에도 '소지품 보관료가 있나요?' 노출됨
<img width="737" alt="스크린샷 2024-06-13 오후 8 21 46" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/bb4314e8-f0c6-4a32-93e7-7ae9d05a40b4">

2. 보관료 숫자 인풋 아래 '저장하기' 버튼 뜨지 않고 '취소하기' 만 노출됨
ㄴ '정보 반영 요청하기' 클릭시 변경된 보관료 정보가 저장되기는 하네요
<img width="745" alt="스크린샷 2024-06-13 오후 8 21 56" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/1c57cd7c-1223-4592-8799-0948e623aa7f">

3. 필수정보를 입력하지 않아도 최하단 '정보 반영 요청하기' 버튼이 활성화 되어 있음
ㄴ 다음화면으로 넘어가지 않고, 입력안된 인풋창으로 이동하기는 하네요!

[개선사항]
1. '보관함이 없어요' 선택 시 '소지품 보관료가 있나요?' 항목 미노출
2. 보관료 금액 인풋 아래 '저장하기' 버튼 추가 필요
3. 필수정보 미입력시 '정보 반영 요청하기' 버튼 비활성화

**Comment by heyman333** [comment]
@Dumbs-app 개발에서 수정완료!

**Comment by Dumbs-app** [comment]
@heyman333 
2번, 3번은 반영이 안된 걸로 보입니다ㅠ!

2. 저장하기버튼 미노출 되고 있음
<img width="703" alt="스크린샷 2024-06-16 오후 7 13 37" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/d711039a-9ecd-4fd0-a510-9b4a4ef4796a">

3. 필수정보 입력 안 한 경우에도 
정보수정요청 반영버튼 활성화 되어있음, 입력 안된 채로 정보수정반영처리 됨

**Comment by heyman333** [comment]
@Dumbs-app 이거 지금 2번은 API가 따로 없어서 지금 이 방식대로 form을 전체로 저정하는 방법으로 가야될거같아요ㅠ.ㅠ 3번은 수정하겠습니다. 1번만 있는줄 알았네요

**Comment by Dumbs-app** [comment]
@txtart 
2번 API 만들라!

**Comment by heyman333** [comment]
> @txtart 2번 API 만들라!

@txtart @Dumbs-app 일단 1차는 이렇게 가야할듯.ㅠㅠ

**Comment by Dumbs-app** [comment]
@heyman333 
옙 그러면 1차에서는 취소하기 버튼도 빠지는게 나을 것 같아요!! (cc. @3d3nch01 이슈 있으면 말씀 주세요~!)
3번은 아래 케이스가 아직 반영이 안된 것 같기는 합니다ㅠ
- 음악장르 미선택시에도 반영 처리 됨
- 필수정보 미입력 시에도 버튼 활성화되어있음

**Comment by heyman333** [comment]
> @heyman333 
> 
> 옙 그러면 1차에서는 취소하기 버튼도 빠지는게 나을 것 같아요!! (cc. @3d3nch01 이슈 있으면 말씀 주세요~!)
> 
> 3번은 아래 케이스가 아직 반영이 안된 것 같기는 합니다ㅠ
> 
> - 음악장르 미선택시에도 반영 처리 됨
> 
> - 필수정보 미입력 시에도 버튼 활성화되어있음

넵 이건 수정할게영

**Comment by Dumbs-app** [comment]
@heyman333 님
요거 3번 이슈용!
회원가입 시에는 잘 작동되고 있는데
로그인해서 정보 수정시에는 작동이 안되고 있는 것 같아용 확인 부탁드립니댜

**Comment by Dumbs-app** [comment]
@heyman333 님
입장료 유의사항 문구 최대글자수가 좀 짧은 것 같아서
최대 30자로 늘려주실 수 있으실까요..!!
(cc. @3d3nch01 이슈있으시면 말씀주세욥)
<img width="746" alt="스크린샷 2024-06-23 오후 3 18 54" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/f4ae9cf0-13da-4cca-aee4-d92e807a6f5b">
