### ISSUE TITLE
[어드민]  대표계정생성>이메일>중복확인이슈

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/MVP_QA#5]
[테스트 환경]
안드로이드>크롬

[현재 문제점]
![KakaoTalk_Photo_2024-06-16-19-23-32 003](https://github.com/Dumbs-app/MVP_QA/assets/162934244/c3530609-1dd7-465b-ba41-1d06e21dbe91)

이메일 형식에 안맞게 입력시 "이메일 주소 형식이 아닙니다." 는 출력 
그후 중복확인 버튼 클릭시

![KakaoTalk_Photo_2024-06-16-19-23-31 002](https://github.com/Dumbs-app/MVP_QA/assets/162934244/aa292c05-e40c-41fe-9928-b8f260d1c813)
이메일 형식이 아님에도 "사용가능한 아이디입니다" 출력 이슈

[개선사항]
이메일 형식이 아닌 아이디 입력시 중복확인 불가하게 수정 개선 필요

**Comment by heyman333** [comment]
@hateyoon 개발서버 수정 완료!
