### ISSUE TITLE
[어드민] 관리자 로그인페이지> 로그인 유지 버튼 이슈

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/MVP_QA#6]
[테스트 환경]
안드로이드>크롬

[현재 문제점]
관리자 로그인페이지>로그인 유지 체크박스 활성>로그인 성공>로그인화면으로 돌아갈시 로그인 유지 비활성화(로그인성공>가게정보 반영 페이지에서 네비바 dumbs아이콘 클릭>관리자 로그인 버튼 클릭)
![KakaoTalk_Photo_2024-06-16-19-53-44 002](https://github.com/Dumbs-app/MVP_QA/assets/162934244/c66c73db-cefb-4135-84a4-6908e41df9c0)
로그인 성공 후
![KakaoTalk_Photo_2024-06-16-19-53-43 001](https://github.com/Dumbs-app/MVP_QA/assets/162934244/da288a4f-92d6-488c-b7b0-9724e1e4f936)
이화면에서 네비바 dumbs 아이콘 클릭>
![KakaoTalk_Photo_2024-06-16-19-56-25](https://github.com/Dumbs-app/MVP_QA/assets/162934244/0ed3d625-4e5b-4448-85e8-dd25516d4856)
관리자 로그인 버튼 클릭시 로그인유지 비활성화
[개선사항]
로그인 유지기능 활성시 다른페이지 넘어가도 로그인 유지되게 개선 필요

**Comment by heyman333** [comment]
@hateyoon 로고 클릭했을 때 홈으로 안가도록 수정하겠습니당
