### ISSUE TITLE
[어드민]>[가게입점하기]>가게정보 페이지 이슈

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/MVP_QA#7]
[테스트 환경]
안드로이드>크롬

[현재 문제점]
![KakaoTalk_Photo_2024-06-16-20-21-23](https://github.com/Dumbs-app/MVP_QA/assets/162934244/5d5773bf-4dab-4310-81ca-48f75f4eb6b1)

예시란에는 "30,000" 쉼표가 활성화 되어있는데

![KakaoTalk_Photo_2024-06-16-20-21-19](https://github.com/Dumbs-app/MVP_QA/assets/162934244/28d9d65c-5e9d-4ff7-b9c8-94cd815c4129)

입력란에 "30000"입력시 쉼표 미적용 이슈, 쉼표 버튼 클릭시 쉼표 미출력 이슈

![KakaoTalk_Photo_2024-06-16-20-21-15](https://github.com/Dumbs-app/MVP_QA/assets/162934244/edf30bf7-9749-4d7b-a23e-cb1a6ce6e343)

입력을 완료해도 "30000"이라고만 입력 이슈

![KakaoTalk_Photo_2024-06-16-20-21-07](https://github.com/Dumbs-app/MVP_QA/assets/162934244/2236a6bc-e791-4d1c-af60-aa4aa7fa2470)

인스타그램 연결 입력칸에 한글 입력 가능 이슈

[개선사항]
가격 입력란 예시란 통일 필요
인스타그램 연결 입력란에 한글 입력 불가 조치 필요

**Comment by heyman333** [comment]
@Dumbs-app @hateyoon 중간에 쉼표 넣는건 지금 상황에서 좀 복잡할거같고 인스타그램 한글 못하게 하는건 수정했습니다ㅠㅠ

**Comment by hateyoon** [comment]
넵 그러면 클로즈하겠습니다.!
