### ISSUE TITLE
[어드민]>[가게정보]>가게 입점하기 페이지 등록 이슈

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/MVP_QA#8]
[테스트 환경]
안드로이드>크롬

[현재 문제점]

https://github.com/Dumbs-app/MVP_QA/assets/162934244/8201593d-133b-47ec-8513-1ec278c03376

가게 기본정보 입력 후 "정보 반영 요청하기" 버튼 클릭 

![KakaoTalk_Photo_2024-06-16-20-36-12](https://github.com/Dumbs-app/MVP_QA/assets/162934244/260f3c6d-2bc5-4838-838d-fa9b263e0c56)
"가입 심사요청에 실패했습니다" 출력 이슈

[개선사항]
무엇이 불충족 되어서 등록이 안되었는지 출력 필요

**Comment by heyman333** [comment]
@hateyoon 수정완료 (개발서버)
