### ISSUE TITLE
[어드민]>[가게입점하기]>영업시간 및 입장료 페이지 이슈 

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/MVP_QA#9]
[테스트 환경]
안드로이드 -크롬

[현재 문제점]

![KakaoTalk_Photo_2024-06-18-18-04-44 001](https://github.com/Dumbs-app/MVP_QA/assets/162934244/74a824e4-45ac-4c04-8432-63aec85cc937)
24 이상 입력 이슈
![KakaoTalk_Photo_2024-06-18-18-04-45 002](https://github.com/Dumbs-app/MVP_QA/assets/162934244/dd57dd57-5c73-402c-837f-16c9e64adbda)
오입력 했는데 등록가능 이슈

[개선사항]
숫자를 시간에 맞게 입력 가능하게 조정
오입력 했을 때 등록 불가하게 조정

**Comment by heyman333** [comment]
@hateyoon 수정완료
